# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptroot";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/804fc135-56ba-43e9-8337-b7ee35bdbf06";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EDEC-EE3A";
      fsType = "vfat";
      options = [ "uid=0" "gid=0" "umask=007" ];
    };

  swapDevices = [ { device = "/swapfile"; size = 8192; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Fix sway: https://discourse.nixos.org/t/egl-ext-platform-base-not-supported-after-upgrade-moving-to-flakes/29521
  hardware.opengl.enable = true;
}
