#!/bin/sh

# Intakes an absolute/relative song path, adds it after the current playing mpd song,
# then skips the current playing song and plays the next one.

# Quit if no arguments
[ $# -eq 0 ] && exit 1

# Run mpd if not running
[ -z "$(pidof mpd)" ] && mpd && wait

# Add to playlist
song="$(realpath -- "$1")"

[ ! -f "$song" ] && {
    notify-send -u critical "mpdplay" "\"$song\" not found"
    exit 1
}
mpc insert "file://$song" >/dev/null 2>&1 || {
    notify-send -u critical "mpdplay" "Failed to add song to queue"
    exit 1
}
mpc next >/dev/null 2>&1 || mpc play >/dev/null 2>&1
