#!/bin/sh -e

# This script instakes a m3u playlist and creates a directory containing all
# files in the same order converted to WAV, ready to be burned to an audio CD.
# A cdrdao config is also generated.
#
# To burn the resulting directory onto a CD:
# https://www.axllent.org/docs/cd-writing-using-cdrecord
#
# Dependencies:
# - ffmpeg

# m3u paths are relative to this directory
rootdir=~/Music

help () {
    printf "Usage:

    pl2cd PLAYLIST [DIR]

    PLAYLIST - an m3u playlist file with paths relative to '%s'

    DIR - The directory to be created, containing all files listed in PLAYLIST
    converted to the right format. If no dir is passed, extensionless name of
    PLAYLIST is used.
" "$rootdir"
}

case "$1" in
    -h|--help) help ; exit ;;
esac

[ $# -lt 1 ] && echo "pl2cd: at least 1 argument required" >&2 && exit 1
[ ! -f "$1" ] && echo "pl2cd: no file found" >&2 && exit 1
dir="${2:-${1%%.m3u}}"
[ -z "$dir" ] && echo "pl2cd: playlist has no filename" >&2 && exit 1
[ -d "$dir" ] && echo "pl2cd: directory \"$dir\" already exists" >&2 && exit 1
mkdir -p "$dir"

cdrdao="$dir/$(echo "$dir" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').cdrdao"
printf '// vim: ft=cdrdaoconf
CD_DA

CD_TEXT {
  LANGUAGE_MAP {
    0 : EN
  }

  LANGUAGE 0 {
    TITLE "%s"
    PERFORMER "Various Artists"
  }
}
' "$dir" >"$cdrdao"
no=1
while read -r f; do
    fpath="$rootdir/$f"
    [ ! -f "$fpath" ] && echo "pl2cd: invalid path found in line $no" >&2 && exit 1
    fname="$(basename -- "$f")"
    npath="$dir/$(printf "%02d" "$no"). ${fname%.*}.wav"
    # Convert to stereo, 44100Hz, 16bit, wav (PCM)
    ffmpeg -nostdin -loglevel error -i "$fpath" -ar 44100 -ac 2 -sample_fmt s16 "$npath"

    title="$(rsid3 --TIT2 -- "$fpath" | sed 's/"/\\"/g')"
    artist="$(rsid3 --TPE1 -- "$fpath" | sed 's/"/\\"/g')"
    {
        echo 'TRACK AUDIO'
        echo 'CD_TEXT {'
        echo 'LANGUAGE 0 {'
        echo "  TITLE \"$title\""
        echo "  PERFORMER \"$artist\""
        echo '  }'
        echo '}'
        echo "FILE \"$(realpath --relative-to "$dir" -- "$npath")\" 0"
        echo
    } >>"$cdrdao"

    no=$(( no + 1 ))
done <"$1"
