#!/bin/sh -e

# This script instakes a m3u playlist and creates
# a directory containing all files in the same order.
#
# Dependencies:
# - rsid3

# m3u paths are relative to this directory
rootdir=~/Music

help () {
    printf "Usage:

    plexport PLAYLIST [DIR]

    PLAYLIST - an m3u playlist file with paths relative to '%s'

    DIR - The directory to be created, containing all files listed in PLAYLIST
    converted to the right format. If no dir is passed, extensionless name of
    PLAYLIST is used.
" "$rootdir"
}

case "$1" in
    -h|--help) help ; exit ;;
esac

[ $# -lt 1 ] && echo "plexport: at least 1 argument required" >&2 && exit 1
[ ! -f "$1" ] && echo "plexport: no file found" >&2 && exit 1
dir="${2:-${1%%.m3u}}"
[ -z "$dir" ] && echo "plexport: playlist has no filename" >&2 && exit 1
[ -d "$dir" ] && echo "plexport: directory \"$dir\" already exists" >&2 && exit 1
mkdir -p "$dir"

no=1
while read -r f; do
    fpath="$rootdir/$f"
    [ ! -f "$fpath" ] && echo "plexport: invalid path found in line $no" >&2 && exit 1

    # Create new filename
    artist_title="$(rsid3 --TPE1 --TIT2 -d -- "$fpath")"
    artist="${artist_title%%*}"
    artist="${artist:-$(basename -- "$(dirname -- "$f")")}"
    title="${artist_title##*}"
    if [ -z "$title" ]; then
        title="$(basename -- "$f")"
        title="${title%.*}"
    fi
    ext="${fpath##*.}"
    npath="$dir/$(printf "%02d" "$no"). $artist - $title.$ext"

    cp -- "$fpath" "$npath"
    echo "$npath"
    no=$(( no + 1 ))
done <"$1"
