#!/bin/sh -e
# Edit the hledger journal

LEDGER="${XDG_DATA_HOME:-$HOME/.local/share}/ledger"
SECRETS="$LEDGER/secrets"

secrets decrypt "$LEDGER"

mkdir -p -- "$SECRETS/$(date +%Y)"
fpath="$SECRETS/$(date +%Y/%Y-%m.journal)"
$EDITOR "+cd $SECRETS" -- "$fpath"
if secrets modified "$LEDGER" >/dev/null; then
    git -C "$SECRETS" add .
    git -C "$SECRETS" commit -m "Update $(realpath --relative-to "$SECRETS" -- "$fpath")"
    secrets save "$LEDGER"
else
    echo 'No changes were made, skipping.'
fi
