#!/bin/sh
# An improved accounting equation report.
# https://hledger.org/balancing-the-accounting-equation.html
set -e

LEDGER="${XDG_DATA_HOME:-$HOME/.local/share}/ledger"

secrets decrypt "$LEDGER"

hledger \
    --real \
    --infer-equity \
    --alias '/^(revenue|income|expenses)\b/=equity' \
    bse not:desc:'closing balances' \
    "$@"
