#!/bin/sh -e
# Show a historical forecast (default: monthly current year)

hledger bal \
    --auto \
    --strict \
    --infer-equity \
    --real \
    --pretty \
    --color=always \
    --period=thisyear \
    --forecast \
    --historical \
    --tree \
    --monthly \
    not:equity \
    "$@" | less -R +g +k
