#!/bin/sh -e
# Show a historical forecast (default: monthly current year)

hledger \
    --auto \
    --strict \
    --infer-equity \
    --real \
    --pretty \
    --color=always \
    --period=thisyear \
    bal --forecast --historical --tree --monthly not:equity \
    "$@" | less -R +g +k
