#!/bin/sh -e
# Show the budget for any time period (default: current month in zł)

hledger bal \
    --auto \
    --strict \
    --infer-equity \
    --real \
    --pretty \
    --color=always \
    --period=thismonth \
    --exchange=zł \
    --budget \
    --layout=tidy \
    --tree \
    "$@"
