{
  hardware.fancontrol = {
    enable = true;
    config = let
      minTemp = "70";
      maxTemp = "85";
      minStart = "60";
      minStop = "0";
    in ''
      # Configuration file generated by pwmconfig
      INTERVAL=5
      DEVPATH=hwmon1=devices/platform/nct6775.2592
      DEVNAME=hwmon1=nct6795
      FCTEMPS=hwmon1/pwm5=hwmon1/device/temp5_input hwmon1/pwm4=hwmon1/device/temp4_input hwmon1/pwm3=hwmon1/device/temp3_input hwmon1/pwm2=hwmon1/device/temp2_input
      FCFANS=hwmon1/pwm5=hwmon1/fan5_input
      MINTEMP=hwmon1/pwm5=${minTemp} hwmon1/pwm4=${minTemp} hwmon1/pwm3=${minTemp} hwmon1/pwm2=${minTemp}
      MAXTEMP=hwmon1/pwm5=${maxTemp} hwmon1/pwm4=${maxTemp} hwmon1/pwm3=${maxTemp} hwmon1/pwm2=${maxTemp}
      MINSTART=hwmon1/pwm5=${minStart} hwmon1/pwm4=${minStart} hwmon1/pwm3=${minStart} hwmon1/pwm2=${minStart}
      MINSTOP=hwmon1/pwm5=${minStop} hwmon1/pwm4=${minStop} hwmon1/pwm3=${minStop} hwmon1/pwm2=${minStop}
    '';
  };

  boot.kernelModules = [ "coretemp" "nct6775" ];
}
