#!/bin/sh -e

# GENerate Stream MUsic List

# This script generates a markdown file of all music stored inside
# the Fair Use playlist.
#
# This script was created so that listing music for various streaming
# platforms is made easier.
#
# DEPENDENCIES:
# - rsid3
# - awk

pl="$HOME/Music/Playlists/#Fair Use.m3u"
base="$HOME/Music"

export OUTFILE="playlist.md"

# Wipe the outfile
printf '' >"$OUTFILE"

while read -r relative; do
    f="$base/$relative"
    [ ! -f "$f" ] && {
        echo "gensmul: Invalid path detected, run plfix" >&2
        exit 1
    }

    # Extract relevant information
    set +e
    tags="$(rsid3 --TPE1 --TIT2 --WXXX origin -- "$f" 2>/dev/null)"
    if [ $? -eq 1 ]; then
        # Exit if any information is missing
        echo "gensmul: tags missing from file '$f'. Aborting."
        exit 1
    fi
    set -e
    artist="$(echo "$tags" | head -n1)"
    title="$(echo "$tags" | head -n2 | tail -n1)"
    url="$(echo "$tags" | tail -n1)"

    # Keep the outfile sorted while adding more lines
    # (method source: https://stackoverflow.com/a/10658677/10792539)
    echo "[$artist - $title]($url)" | sort -o "$OUTFILE" -m - "$OUTFILE"
done <"$pl"

# Add markdown list numbering
tmpfile="/tmp/$(basename "$0")_awk"
awk 'BEGIN{i=1} /.*/{printf "%d. % s\n",i,$0; i++}' "$OUTFILE" > "$tmpfile"
mv -- "$tmpfile" "$OUTFILE"
