{
  programs.lf.enable = true;

  xdg.configFile."lf/lfrc".source = ./lfrc;
  xdg.configFile."lf/icons".text = ''
    di        📁
    fi        📃
    tw        🤝
    ow        📂
    ln        📎
    or        ❌
    ex        👾
    *Makefile               ⚒️
    *makefile               ⚒️
    *GNUmakefile            ⚒️
    *CMakeLists.txt         ⚒️
    *Kconfig                ⚒️
    *Kbuild                 ⚒️
    *Dockerfile             🐋
    *Cargo.lock             🦀
    *Cargo.toml             🦀
    *clippy.toml            🦀
    *rustfmt.toml           🦀
    *requirements.txt       🐍
    *flake.lock             ❄️
    *README                 📝
    *LICENSE                ©️
    *CHANGELOG              📝
    *CONTRIBUTING           📝
    *SUPPORT                📝
    *CONTRIBUTORS           📝
    *AUTHORS                📝
    *ACKNOWLEDGEMENTS       📝
    *ISSUE_TEMPLATE         📝
    *PULL_REQUEST_TEMPLATE  📝
    *CODEOWNERS             📝
    *OWNERS                 📝
    *CREDITS                📝
    *MAINTAINERS            📝
    *COPYING                📝
    *.txt                   📝
    *.md                    📝
    *.MD                    📝
    *.journal               🧾
    *.ldg                   🧾
    *.bib                   📜
    *.pdf                   📚
    *.djvu                  📚
    *.epub                  📚
    *.srt                   📜
    *.vtt                   📜
    *.png                   "🖼 "
    *.gif                   "🖼 "
    *.ico                   "🖼 "
    *.svg                   🧬
    *.eps                   🧬
    *.jpg                   📸
    *.jpeg                  📸
    *.wav                   🎵
    *.mp3                   🎵
    *.opus                  🎵
    *.ogg                   🎵
    *.m4a                   🎵
    *.flac                  🎵
    *.mp4                   🎥
    *.mkv                   🎥
    *.webm                  🎥
    *.mpeg                  🎥
    *.mpg                   🎥
    *.avi                   🎥
    *.mov                   🎥
    *.wmv                   🎥
    *.asf                   🎥
    *.flv                   🎥
    *.m4v                   🎥
    *.qt                    🎥
    *.3gp                   🎥
    *.xcf                   🎨
    *.kra                   🎨
    *.ase                   👻
    *.aseprite              👻
    *.ods                   📊
    *.xls                   📊
    *.xlsx                  📊
    *.ardour                ⛺
    *.ove                   🫒
    *.h2song                🥁
    *.ipynb                 📗
    *.css                   🎨
    *.html                  🌐
    *.zig                   ⚡
    *.rs                    🦀
    *.py                    🐍
    *.nix                   ❄️
    *.patch                 🩹
    *.lua                   🧿
    *.bin                   ⬛
    *.dat                   ⬛
    *.so                    🧰
    *.a                     🧰
    *.so.*                  🧰
    *.a.*                   🧰
    *.o                     ◼️
    *.conf                  ⚙️
    *.config                ⚙️
    *.xml                   ⚙️
    *.toml                  ⚙️
    *.yaml                  ⚙️
    *.ini                   ⚙️
    *.csv                   ⚙️
    *.json                  ⚙️
    *.1                     ℹ️
    *.2                     ℹ️
    *.3                     ℹ️
    *.4                     ℹ️
    *.5                     ℹ️
    *.6                     ℹ️
    *.7                     ℹ️
    *.8                     ℹ️
    *.9                     ℹ️
    *.nfo                   ℹ️
    *.info                  ℹ️
    *.zip                   📦
    *.rar                   📦
    *.7z                    📦
    *.gz                    📦
    *.bz                    📦
    *.xz                    📦
    *.deb                   📦
    *.jar                   📦
    *.pak                   📦
    *.ispm                  📦
    *.iso                   📀
    *.img                   📀
    *.db                    🗃️
    *.db3                   🗃️
    *.sqlite                🗃️
    *.sqlite3               🗃️
    *.bak                   🗄️
    *.gpg                   🔒
    *.asc                   🔒
    *.lock                  🔒
    *.pub                   🔑
    *.sig                   🪪
    *.torrent               🔽
    *.part                  💔
    *.ninja                 ⚒️
    *.trashinfo             🗑️
  '';

  home.file.".scripts/genlfjmp".source = ./genlfjmp;
  home.file.".scripts/lf-previewer".source = ./lf-previewer;
}
