#!/bin/sh -e

bookdir=~/Documents/Books

book="$(find "$bookdir" -type f -name '*.pdf' -exec basename -- '{}' \; | bemenu -p "Open book:")"

[ -n "$book" ] && $PDF_READER "$(find "$bookdir" -type f -name "$book" -print -quit)"
