#!/bin/sh -e

# Unstage all changes to flake or direnv related files.
# Add flake.nix and flake.lock to the staging area with --intent-to-add.
# This script makes it so that flake.nix and flake.lock are in the git staging
# area, but it's safe to commit without them being included.

git_root="$(git rev-parse --show-toplevel)"

for fname in flake.nix flake.lock .direnv .envrc; do
    fpath="$git_root/$fname"
    if [ -e "$fpath" ]; then
        git reset --quiet -- "$fpath"
    fi
done

for fname in flake.nix flake.lock; do
    fpath="$git_root/$fname"
    if [ -f "$fpath" ]; then
        git add --intent-to-add --force -- "$fpath"
    fi
done
