#!/bin/sh
# Edit the ledger journal
set -e

LEDGER="${XDG_DATA_HOME:-$HOME/.local/share}/ledger"
SECRETS="$LEDGER/secrets"

secrets "$LEDGER" decrypt

mkdir -p -- "$SECRETS/$(date +%Y)"
fpath="$SECRETS/$(date +%Y/%Y-%m.ldg)"
$EDITOR "+cd $SECRETS" -- "$fpath"
if secrets "$LEDGER" modified >/dev/null; then
    git -C "$SECRETS" add .
    git -C "$SECRETS" commit -m "Update $(realpath --relative-to "$SECRETS" -- "$fpath")"
    secrets "$LEDGER" save
else
    echo 'No changes were made, skipping.'
fi
