#!/bin/sh -e

if [ $# -eq 0 ]; then
    if [ -f flake.nix ]; then
        exec nix shell
    elif [ -f shell.nix ]; then
        exec nix-shell
    else
        echo 'ns: flake.nix and shell.nix missing in the current directory' >&2
        exit 1
    fi
fi

cmd='nix shell'

for arg in "$@"; do
    arg_sanitized="$(echo "$arg" | tr -cd '[:alnum:]+-._?=')"
    if [ "$arg" != "$arg_sanitized" ]; then
        echo "ns: illegal package name '$arg'" >&2
        exit 1
    fi
    cmd="$cmd nixpkgs#'$arg_sanitized'"
done

eval "exec $cmd"
