#!/bin/sh -e

# This script can be run by window managers to
# easily perform common operations such as shutting
# down, restarting, logging out etc.

case "$(printf "%s\n" "poweroff" "reboot" "suspend" "logout" | bemenu -p 'quitmenu')" in
    "poweroff") systemctl poweroff ;;
    "reboot") systemctl reboot ;;
    "suspend") systemctl suspend ;;
    "logout") swaymsg exit ;;
esac
