#!/bin/sh
# A little script to help with gpg-encrypted directories.
set -e

help () {
    echo 'Usage:  secrets [-h,--help] DIR ACTION'
    echo
    echo 'Actions:'
    echo "  d|decrypt   Decrypt secrets.gpg into a tmpdir and symlink as secrets."
    echo "  s|save      Overwrite secrets.gpg to reflect the decrypted secrets."
    echo "  c|clean     Same as save, but also destroy the tmpdir and symlink."
}

# Handle printing help
[ "$1" = '-h' ] || [ "$1" = '--help' ] && help && exit
[ $# -ne 2 ] && help && exit 1


REPO="$1"
[ ! -d "$REPO" ] && {
    echo 'secrets: the repository directory does not exist' >&2
    exit 2
}
GPGID_E="$(cat -- "$REPO/.gpgid-encrypt")"
GPGID_S="$(cat -- "$REPO/.gpgid-sign")"
SECRETS="$REPO/secrets"
SECRETS_GPG="$REPO/secrets.gpg"
CHECKSUM="$REPO/.cksum"
ACTION="$2"

# Credit: https://stackoverflow.com/a/545413/10792539
dir_cksum () {
    find "$1" -type f -print0 \! -path '*/.git/*' \
        | sort -z | xargs -0 cat | sha1sum
}

decrypt () {
    if [ -L "$SECRETS" ]; then
        echo 'secrets: the secrets are already decrypted -- skipping' >&2
        return
    elif [ -e "$SECRETS" ]; then
        printf "secrets: a file with a conflicting name '%s' already exists -- aborting\n" "$SECRETS" >&2
        exit 1
    fi

    tmpd="$(mktemp --tmpdir -d note-secrets.XXXXX)"

    gpg --decrypt -- "$SECRETS_GPG" | tar -xzf - -C "$tmpd"
    dir_cksum "$tmpd" >.cksum
    ln -s -- "$tmpd/secrets" "$SECRETS"

    echo
    tput bold setaf 9
    echo "! $(echo "$SECRETS" | sed "s$HOME~") DECRYPTED !"
    tput sgr0
    printf 'To make changes persistent, remember to run %s...\n' \
        "$(tput setaf 6)secrets DIR save $(tput sgr0)"
}

clean () {
    save

    secrets_dir="$(readlink -- "$SECRETS")"
    # Make sure secrets_dir/.. is a subdirectory of TMPDIR,
    # because the next step is a little scary
    tmpd="$(realpath -- "$secrets_dir/..")"
    if [ -n "$(find "${TMPDIR:-/tmp}" -path "$tmpd/*" -print -quit 2>/dev/null)" ]; then
        rm -rf -- "$tmpd"
    else
        printf 'secrets: error! secrets_dir/.. is not a subdirector of TMPDIR, this should not happen (%s)\n' "$tmpd" >&2
        exit 2
    fi
    rm -rf -- "$SECRETS" "$CHECKSUM"

    echo
    tput bold setaf 2
    echo "$(echo "$SECRETS" | sed "s$HOME~") encrypted"
    tput sgr0
}

save () {
    # Error handling
    if [ ! -L "$SECRETS" ]; then
        echo 'secrets: the secrets are already locked' >&2
        return
    fi
    secrets_dir="$(readlink -- "$SECRETS")"
    if [ ! -d "$secrets_dir" ]; then
        printf 'secrets: error! the secrets symlink does not point to a directory\n' >&2
        exit 2
    fi

    # Check if any secrets have been modified and need re-encrypting.
    # Aside from a performance boost, this is necessary due to gpg encryption being
    # non-deterministic (there's probably some salt involved).
    prev_cksum="$(cat -- "$CHECKSUM" 2>/dev/null || :)"
    new_cksum="$(dir_cksum "$secrets_dir")"
    if [ "$new_cksum" != "$prev_cksum" ]; then
        printf 'Secrets were modified, re-encrypting... '
        tmp="$(mktemp --tmpdir note-encrypt.XXXXX)"
        tar -C "$(dirname -- "$secrets_dir")" -czf "$tmp" -- "$(basename -- "$secrets_dir")"
        gpg --yes --output "$SECRETS.gpg" --encrypt --recipient "$GPGID_E" --sign --local-user "$GPGID_S" -- "$tmp"
        echo "$new_cksum" >"$CHECKSUM"
        rm -f -- "$tmp"
        echo 'done.'
    else
        echo 'No changes to secrets were made.'
    fi
}

case "$ACTION" in
    d|decrypt) decrypt ;;
    s|save) save ;;
    c|clean) clean ;;
    *)
        echo 'secrets: invalid action' >&2
        help
        exit 1
esac
