#!/bin/sh -e

col1=2
col2=11
scount=3

# This file stores which flake profile to build
NIXOS_FLAKE_PROFILE=~/.config/nixos-config-profile

section () {
    printf "$(tput setaf $col1)$(tput bold)(%s/%s) %s $(tput setaf $col2)%s$(tput setaf $col1)...$(tput sgr0)\n" "$snow" "$scount" "$1" "$2"
}

sectionend() {
    snow=$(( snow + 1 ))
    printf "\n"
}

# Figure out NixOS flake profile
if [ ! -f "$NIXOS_FLAKE_PROFILE" ]; then
    # shellcheck disable=SC2088
    printf '~/.config/nixos-config-profile not found. Which one to use?\n> '
    read -r profile
    echo "$profile" >"$NIXOS_FLAKE_PROFILE"
    printf "Stored '%s' in %s\n" "$profile" "$NIXOS_FLAKE_PROFILE"
else
    profile="$(cat -- "$NIXOS_FLAKE_PROFILE")"
    printf "Using profile '%s' from %s\n" "$profile" "$NIXOS_FLAKE_PROFILE"
fi

# Check preemptively if Cachix is configured for the final step
if [ ! -f "${XDG_CONFIG_HOME:-$HOME/.config}/cachix/cachix.dhall" ] && [ -z "$CACHIX_SIGNING_KEY" ]; then
    echo
    echo   '│ Cachix signing key is not configured. To have the cache updated, run this first:'
    echo   '│'
    echo   '│ $  pass websites/cachix.org | tail -n1 | cachix authtoken --stdin'
    echo   '│'
    printf '│ Run the above command? [y/N] '
    read -r ans
    if [ "$ans" = y ] || [ "$ans" = Y ]; then
        pass websites/cachix.org | tail -n1 | cachix authtoken --stdin
    else
        echo '│'
        echo '│ Continuing without Cachix ...'
        echo
    fi
fi

# Refresh superuser privilages
sudo true

snow=1

section UPDATING 'NixOS flake'
{
    if command -v nh >/dev/null; then
        nh os switch --accept-flake-config --update --ask --hostname "$profile" ~/nixos-config/
    else
        cd ~/nixos-config/
        nix flake update
        sudo nixos-rebuild switch --accept-flake-config --flake ~/nixos-config#"$profile"
    fi
}
sectionend

section UPDATING 'neovim plugins'
{
    set +e
    nvim --headless +'autocmd User PaqDoneSync qall' +PaqSync
    echo
    nvim --headless +TSUpdate +qall
    echo
}
sectionend

section PUSHING 'binaries to Cachix'
{
    set +e
    nix-store -qR /run/current-system/ | grep \
        -e '-rsid3-' \
        -e '-music-tools-' \
        -e '-aseprite-' \
        -e '-obs-studio-' \
        -e '-ncmpcpp-' \
    | xargs nix-store -qR | cachix push pcache
}
sectionend
