#!/bin/sh

col1=2
col2=11
scount=3

section () {
    printf "$(tput setaf $col1)$(tput bold)(%s/%s) %s $(tput setaf $col2)%s$(tput setaf $col1)...$(tput sgr0)\n" "$snow" "$scount" "$1" "$2"
}

sectionend() {
    snow=$(( snow + 1 ))
    printf "\n"
}

# Refresh superuser privilages
sudo true

snow=1

set -e
section UPDATING 'NixOS flake.lock'
cd ~/nixos-config/
nix flake update
sectionend

section REBUILDING 'NixOS flake'
sudo nixos-rebuild switch --flake ~/nixos-config#default
sectionend
set +e

section UPDATING 'neovim plugins'
nvim --headless +'autocmd User PaqDoneSync qall' +PaqSync
echo
nvim --headless +TSUpdateSync +qall
echo
nvim --headless +COQdeps +qall
echo
sectionend
