#!/bin/sh -e

col1=2
col2=11
scount=3

# This file stores which flake profile to build
NIXOS_FLAKE_PROFILE=~/.config/nixos-config-profile

section () {
    printf "$(tput setaf $col1)$(tput bold)(%s/%s) %s $(tput setaf $col2)%s$(tput setaf $col1)...$(tput sgr0)\n" "$snow" "$scount" "$1" "$2"
}

sectionend() {
    snow=$(( snow + 1 ))
    printf "\n"
}

# Figure out NixOS flake profile
if [ ! -f "$NIXOS_FLAKE_PROFILE" ]; then
    printf '~/.config/nixos-config-profile not found. Which one to use?\n> '
    read -r profile
    echo "$profile" >"$NIXOS_FLAKE_PROFILE"
    printf "Stored '%s' in %s\n" "$profile" "$NIXOS_FLAKE_PROFILE"
else
    profile="$(cat -- "$NIXOS_FLAKE_PROFILE")"
    printf "Using profile '%s' from %s\n" "$profile" "$NIXOS_FLAKE_PROFILE"
fi

# Refresh superuser privilages
sudo true

snow=1

set -e
section UPDATING 'NixOS flake'
if command -v nh >/dev/null; then
    nh os switch --update --ask --hostname "$profile" ~/nixos-config/
else
    cd ~/nixos-config/
    nix flake update
    sudo nixos-rebuild switch --flake ~/nixos-config#"$profile"
fi
sectionend
set +e

section UPDATING 'neovim plugins'
nvim --headless +'autocmd User PaqDoneSync qall' +PaqSync
echo
nvim --headless +TSUpdateSync +qall
echo
nvim --headless +COQdeps +qall
echo
sectionend
